# Generated by Django 5.0.2 on 2024-05-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUnsetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_field', models.FloatField()),
                ('int_field', models.IntegerField()),
            ],
        ),
    ]
