# Generated by Django 5.0.2 on 2024-05-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_testunsetfield'),
        ('school', '0003_student_update_datetime'),
    ]

    operations = [
    ]
