# Generated by Django 5.0.6 on 2024-06-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_student_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
