# Generated by Django 5.1 on 2024-08-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
