# Generated by Django 5.1 on 2024-09-01 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='school.parent')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='school.parent')),
            ],
        ),
    ]
