# Generated by Django 5.1.3 on 2024-11-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_parent_child'),
        ('school', '0009_student_age'),
    ]

    operations = [
    ]
