# Generated by Django 5.1.3 on 2024-11-12 16:19

import eventlog.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
            ],
            bases=(eventlog.mixins.LoggerMixin, models.Model),
        ),
    ]
