# Generated by Django 5.1.3 on 2024-11-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
    ]
