# Generated by Django 5.1.4 on 2024-12-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_klass_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='father_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
