# Generated by Django 5.1.6 on 2025-03-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_child_father_name_parent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('other', models.JSONField()),
            ],
        ),
    ]
